// START-MUGUR-REGION

#include QMK_KEYBOARD_H
#include "version.h"

      /* Macros */


      /* Tap Dances */


      /* Leader Keys */


      /* Combos */


      /* Layer Codes and Matrix */
enum layer_codes {BASE, LAYER1, LAYER2, LAYER3};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

[BASE] = LAYOUT_ortho_4x12
(
 KC_TAB, KC_A, KC_Z, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPACE,
 MT(MOD_LCTL, KC_ESCAPE), KC_Q, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_M, KC_ENTER,
 KC_LSFT, KC_W, KC_X, KC_C, KC_V, KC_B, KC_N, KC_QUOTE, KC_SLASH, KC_SCLN, KC_BSLASH, LT(LAYER3, KC_MINUS),
 KC_LCTL, KC_HYPR, KC_LGUI, KC_LALT, LT(LAYER1, KC_COMMA), KC_SPACE, KC_RALT, LT(LAYER2, KC_DOT), KC_LEFT, KC_DOWN, KC_UP, KC_RIGHT
 ),

[LAYER1] = LAYOUT_ortho_4x12
(
 KC_TAB, KC_NO, KC_AMPERSAND, KC_HASH, KC_MINUS, KC_LEFT_PAREN, KC_RIGHT_PAREN, KC_LEFT_ANGLE_BRACKET, KC_RIGHT_ANGLE_BRACKET, KC_PERCENT, KC_AT, KC_BSPACE,
 MT(MOD_LCTL, KC_ESCAPE), KC_GRAVE, KC_TILDE, KC_PLUS, KC_ASTERISK, KC_LBRACKET, KC_RBRACKET, KC_NO, KC_NO, KC_DOUBLE_QUOTE, KC_UNDERSCORE, KC_ENTER,
 KC_LSFT, KC_NO, KC_EXCLAIM, KC_SLASH, KC_EQUAL, KC_LEFT_CURLY_BRACE, KC_RIGHT_CURLY_BRACE, KC_DOLLAR, KC_BSLASH, KC_PIPE, KC_UP, KC_NO,
 KC_LCTL, KC_HYPR, KC_LGUI, KC_LALT, LT(LAYER1, KC_COMMA), KC_SPACE, KC_RSHIFT, LT(LAYER2, KC_DOT), KC_RALT, KC_LEFT, KC_DOWN, KC_RIGHT),

[LAYER2] = LAYOUT_ortho_4x12
(
 KC_TAB, KC_F1, KC_F2, KC_F3, KC_F4, KC_HOME, KC_END, KC_7, KC_8, KC_9, KC_NO, KC_BSPACE,
 MT(MOD_LCTL, KC_ESCAPE), KC_F5, KC_F6, KC_F7, KC_F8, KC_PGUP, KC_PGDOWN, KC_4, KC_5, KC_6, KC_NO, KC_ENTER,
 KC_LSFT, KC_F9, KC_F10, KC_F11, KC_F12, KC_NO, KC_0, KC_1, KC_2, KC_3, KC_UP, KC_NO,
 KC_LCTL, KC_HYPR, KC_LGUI, KC_LALT, KC_NO, KC_SPACE, KC_LSFT, KC_NO, KC_RCTRL, KC_LEFT, KC_DOWN, KC_RIGHT
 ),

[LAYER3] = LAYOUT_ortho_4x12(RESET, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RGB_TOG, RGB_MOD, RGB_RMOD, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO)
};

// END-MUGUR-REGION
